import { Inter } from "next/font/google";
import "./globals.css";
import { initializeApp } from "firebase/app";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const firebaseConfig = {
  apiKey: "AIzaSyA7V6wwJZ_7TF8lNyGO3nwM87SagmWl_Ps",
  authDomain: "food-translate-3aba3.firebaseapp.com",
  projectId: "food-translate-3aba3",
  storageBucket: "food-translate-3aba3.appspot.com",
  messagingSenderId: "548974436864",
  appId: "1:548974436864:web:2998ce91add5312b53eee5",
  measurementId: "G-3EEMYEMC16",
};

const app = initializeApp(firebaseConfig);
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
